package com.openbible.data.db

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.openbible.data.db.converter.Converters
import com.openbible.data.db.dao.BibleDao
import com.openbible.data.db.dao.BookmarkDao
import com.openbible.data.db.dao.CrossReferenceDao
import com.openbible.data.db.dao.HighlightDao
import com.openbible.data.db.dao.LocationDao
import com.openbible.data.db.dao.NoteDao
import com.openbible.data.db.dao.ParallelTraditionDao
import com.openbible.data.db.dao.ReadingHistoryDao
import com.openbible.data.db.dao.ReadingPlanDao
import com.openbible.data.db.dao.StrongDao
import com.openbible.data.db.entity.BibleLocationEntity
import com.openbible.data.db.entity.BookEntity
import com.openbible.data.db.entity.BookmarkEntity
import com.openbible.data.db.entity.CrossReferenceEntity
import com.openbible.data.db.entity.HighlightEntity
import com.openbible.data.db.entity.LocationEventEntity
import com.openbible.data.db.entity.NoteEntity
import com.openbible.data.db.entity.NoteImageEntity
import com.openbible.data.db.entity.NoteVerseLinkEntity
import com.openbible.data.db.entity.NotebookEntity
import com.openbible.data.db.entity.ParallelTraditionEntity
import com.openbible.data.db.entity.ReadingHistoryEntity
import com.openbible.data.db.entity.ReadingPlanDayEntity
import com.openbible.data.db.entity.ReadingPlanEntity
import com.openbible.data.db.entity.ReadingProgressEntity
import com.openbible.data.db.entity.StrongNumberEntity
import com.openbible.data.db.entity.TranslationEntity
import com.openbible.data.db.entity.VerseEntity
import com.openbible.data.db.entity.VerseLocationLinkEntity
import com.openbible.data.db.entity.VerseStrongLinkEntity

/**
 * OpenBible Room database.
 *
 * Schema is prepopulated with Bible text via createFromAsset().
 * The prepopulated database file lives at assets/databases/openbible.db
 * and is generated by a separate data import pipeline (see docs/).
 *
 * Version 1: initial schema with all 14 entities.
 * Version 2: added cross_references table.
 * Version 3: added strong_numbers and verse_strong_links tables.
 * Version 4: added BBE and NKJV translation metadata entries.
 * Version 5: added locations and verse_location_links tables.
 * Version 6: added FTS5 virtual tables for full-text search per translation.
 * Version 7: added location_events table for biblical events at each location.
 * Version 8: added parallel_traditions table for cross-cultural comparisons.
 * Version 9: removed FK constraint from parallel_traditions (conflicted with
 *            createFromAsset + sequential data importer flow at first boot).
 */
@Database(
    entities = [
        TranslationEntity::class,
        BookEntity::class,
        VerseEntity::class,
        BookmarkEntity::class,
        CrossReferenceEntity::class,
        HighlightEntity::class,
        NoteEntity::class,
        NoteImageEntity::class,
        NoteVerseLinkEntity::class,
        NotebookEntity::class,
        ReadingPlanEntity::class,
        ReadingPlanDayEntity::class,
        ReadingProgressEntity::class,
        ReadingHistoryEntity::class,
        StrongNumberEntity::class,
        VerseStrongLinkEntity::class,
        BibleLocationEntity::class,
        VerseLocationLinkEntity::class,
        LocationEventEntity::class,
        ParallelTraditionEntity::class
    ],
    version = 10,
    exportSchema = true
)
@TypeConverters(Converters::class)
abstract class OpenBibleDatabase : RoomDatabase() {

    abstract fun bibleDao(): BibleDao
    abstract fun bookmarkDao(): BookmarkDao
    abstract fun crossReferenceDao(): CrossReferenceDao
    abstract fun highlightDao(): HighlightDao
    abstract fun noteDao(): NoteDao
    abstract fun readingPlanDao(): ReadingPlanDao
    abstract fun readingHistoryDao(): ReadingHistoryDao
    abstract fun strongDao(): StrongDao
    abstract fun locationDao(): LocationDao
    abstract fun parallelTraditionDao(): ParallelTraditionDao

    companion object {
        private const val DATABASE_NAME = "openbible.db"

        /**
         * Thread-safe singleton. Uses double-checked locking with @Volatile.
         * The prepopulated database is copied from assets on first access
         * if it exists — this is handled transparently by Room.
         */
        @Volatile
        private var INSTANCE: OpenBibleDatabase? = null

        fun getInstance(context: Context): OpenBibleDatabase {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: buildDatabase(context).also { INSTANCE = it }
            }
        }

        private fun buildDatabase(context: Context): OpenBibleDatabase {
            val builder = Room.databaseBuilder(
                context.applicationContext,
                OpenBibleDatabase::class.java,
                DATABASE_NAME
            )

            // Attempt to use prepopulated database from assets
            try {
                context.assets.open("databases/$DATABASE_NAME").use { }
                builder.createFromAsset("databases/$DATABASE_NAME")
            } catch (_: Exception) {
                // No prepopulated database found — will create empty schema.
                // Bible text must be imported via the data pipeline.
            }

            // Explicit migrations — never destroy user data.
            builder.addMigrations(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4, MIGRATION_4_5, MIGRATION_5_6, MIGRATION_6_7, MIGRATION_7_8, MIGRATION_8_9, MIGRATION_9_10)

            return builder.build()
        }

        /**
         * Use in tests to inject a prebuilt instance.
         */
        fun setTestInstance(database: OpenBibleDatabase?) {
            INSTANCE = database
        }

        // ── Migrations ──────────────────────────────────────────

        /**
         * Version 1 → 2: Added cross_references table.
         * Schema matches CrossReferenceEntity.
         * Safe to run multiple times (CREATE TABLE IF NOT EXISTS).
         */
        private val MIGRATION_1_2 = Migration(1, 2) { db ->
            db.execSQL("""
                CREATE TABLE IF NOT EXISTS cross_references (
                    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    fromVerseId INTEGER NOT NULL,
                    toBookId INTEGER NOT NULL,
                    toChapter INTEGER NOT NULL,
                    toVerseStart INTEGER NOT NULL,
                    toVerseEnd INTEGER,
                    relevance INTEGER NOT NULL DEFAULT 0
                )
            """)
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_cross_refs_from ON cross_references(fromVerseId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_cross_refs_to ON cross_references(toBookId, toChapter, toVerseStart)")
        }

        /**
         * Version 3 → 4: Adds BBE and NKJV translation metadata.
         *
         * These translations already exist in the prepopulated DB (v2),
         * so existing installs at v3 will get them added here.
         * Verse data for BBE/NKJV must be imported separately via
         * TranslationImporter (from separate SQLite database files in assets).
         */
        private val MIGRATION_3_4 = Migration(3, 4) { db ->
            db.execSQL("""
                INSERT OR IGNORE INTO translations (id, name, abbreviation, language, copyright, isPublicDomain, isBundled)
                VALUES ('bbe', 'Bible in Basic English', 'BBE', 'en', 'Public domain', 1, 1)
            """)
            db.execSQL("""
                INSERT OR IGNORE INTO translations (id, name, abbreviation, language, copyright, isPublicDomain, isBundled)
                VALUES ('nkjv', 'New King James Version', 'NKJV', 'en', 'Copyright © 1982 Thomas Nelson', 0, 1)
            """)
        }

        /**
         * Version 2 → 3: Added strong_numbers and verse_strong_links tables.
         * These tables support Strong's Concordance lookups.
         * Safe to run multiple times (CREATE TABLE IF NOT EXISTS).
         */
        private val MIGRATION_2_3 = Migration(2, 3) { db ->
            db.execSQL("""
                CREATE TABLE IF NOT EXISTS strong_numbers (
                    number TEXT NOT NULL PRIMARY KEY,
                    lemma TEXT NOT NULL,
                    transliteration TEXT NOT NULL,
                    pronunciation TEXT,
                    part_of_speech TEXT,
                    definition TEXT NOT NULL,
                    derivation TEXT,
                    usageCount INTEGER NOT NULL DEFAULT 0,
                    language TEXT NOT NULL
                )
            """)
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_strong_lemma ON strong_numbers(lemma)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_strong_translit ON strong_numbers(transliteration)")

            db.execSQL("""
                CREATE TABLE IF NOT EXISTS verse_strong_links (
                    verseId INTEGER NOT NULL,
                    strongNumber TEXT NOT NULL,
                    wordPosition INTEGER NOT NULL,
                    originalWord TEXT NOT NULL,
                    transliteration TEXT,
                    PRIMARY KEY (verseId, strongNumber, wordPosition)
                )
            """)
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_vsl_strong ON verse_strong_links(strongNumber)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_vsl_verse ON verse_strong_links(verseId)")
        }

        /**
         * Version 5 → 6: Added FTS5 virtual tables for full-text search per translation.
         * These tables provide fast, ranked full-text search across verses.
         * Safe to run multiple times (CREATE VIRTUAL TABLE IF NOT EXISTS).
         */
        /**
         * Version 6 → 7: Added location_events table for biblical events.
         * Each event is tied to a location and has a narrative description,
         * category, era, and Bible reference for navigation.
         * Schema matches LocationEventEntity.
         */
        private val MIGRATION_6_7 = Migration(6, 7) { db ->
            db.execSQL("""
                CREATE TABLE IF NOT EXISTS location_events (
                    id TEXT NOT NULL PRIMARY KEY,
                    locationId TEXT NOT NULL,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    reference TEXT NOT NULL,
                    bookId INTEGER NOT NULL,
                    chapter INTEGER NOT NULL,
                    category TEXT NOT NULL,
                    era TEXT NOT NULL,
                    sortOrder INTEGER NOT NULL DEFAULT 0
                )
            """)
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_events_location ON location_events(locationId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_events_era ON location_events(era)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_events_category ON location_events(category)")
        }

        /**
         * Version 7 → 8: Added parallel_traditions table for cross-cultural
         * comparisons. Schema matches ParallelTraditionEntity.
         * Safe to run multiple times (CREATE TABLE IF NOT EXISTS).
         */
        private val MIGRATION_7_8 = Migration(7, 8) { db ->
            db.execSQL("""
                CREATE TABLE IF NOT EXISTS parallel_traditions (
                    id TEXT NOT NULL PRIMARY KEY,
                    eventId TEXT,
                    biblicalReference TEXT NOT NULL,
                    biblicalBookId INTEGER NOT NULL,
                    biblicalChapter INTEGER NOT NULL,
                    culture TEXT NOT NULL,
                    documentName TEXT NOT NULL,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    similarities TEXT NOT NULL,
                    differences TEXT NOT NULL,
                    scholarlyNote TEXT,
                    dateRange TEXT,
                    category TEXT NOT NULL,
                    sortOrder INTEGER NOT NULL DEFAULT 0
                )
            """)
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_parallels_event ON parallel_traditions(eventId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_parallels_culture ON parallel_traditions(culture)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_parallels_category ON parallel_traditions(category)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_parallels_book ON parallel_traditions(biblicalBookId)")
        }

        /**
         * Version 8 → 9: Drop the FK constraints from location_events and
         * parallel_traditions.
         *
         * MIGRATION_6_7 / MIGRATION_7_8 created those FKs, but the entities
         * declare none (Room's createFromAsset + sequential importers conflict
         * with FK enforcement; integrity is maintained by the import pipeline).
         * The exported v9 schema therefore expects no FK. Leaving the FK in the
         * migrated table makes Room's post-migration schema validation fail on
         * upgrade — a hard crash for v7/v8 users.
         *
         * SQLite cannot ALTER TABLE DROP CONSTRAINT portably, so both tables are
         * rebuilt without the FK. Idempotent: safe whether or not the FK exists.
         */
        private val MIGRATION_8_9 = Migration(8, 9) { db ->
            // location_events
            db.execSQL("""
                CREATE TABLE location_events_new (
                    id TEXT NOT NULL PRIMARY KEY,
                    locationId TEXT NOT NULL,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    reference TEXT NOT NULL,
                    bookId INTEGER NOT NULL,
                    chapter INTEGER NOT NULL,
                    category TEXT NOT NULL,
                    era TEXT NOT NULL,
                    sortOrder INTEGER NOT NULL DEFAULT 0
                )
            """)
            db.execSQL("INSERT INTO location_events_new SELECT * FROM location_events")
            db.execSQL("DROP TABLE location_events")
            db.execSQL("ALTER TABLE location_events_new RENAME TO location_events")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_events_location ON location_events(locationId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_events_era ON location_events(era)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_events_category ON location_events(category)")

            // parallel_traditions
            db.execSQL("""
                CREATE TABLE parallel_traditions_new (
                    id TEXT NOT NULL PRIMARY KEY,
                    eventId TEXT,
                    biblicalReference TEXT NOT NULL,
                    biblicalBookId INTEGER NOT NULL,
                    biblicalChapter INTEGER NOT NULL,
                    culture TEXT NOT NULL,
                    documentName TEXT NOT NULL,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    similarities TEXT NOT NULL,
                    differences TEXT NOT NULL,
                    scholarlyNote TEXT,
                    dateRange TEXT,
                    category TEXT NOT NULL,
                    sortOrder INTEGER NOT NULL DEFAULT 0
                )
            """)
            db.execSQL("INSERT INTO parallel_traditions_new SELECT * FROM parallel_traditions")
            db.execSQL("DROP TABLE parallel_traditions")
            db.execSQL("ALTER TABLE parallel_traditions_new RENAME TO parallel_traditions")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_parallels_event ON parallel_traditions(eventId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_parallels_culture ON parallel_traditions(culture)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_parallels_category ON parallel_traditions(category)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_parallels_book ON parallel_traditions(biblicalBookId)")
        }

        /**
         * Version 9 → 10: switch `books` to a composite primary key
         * (translationId, id) so every translation owns its own 66 book rows.
         *
         * The v9 table used a single-column PK (id) holding only the kjv rows,
         * so every other translation had an empty book list. Rebuild with the
         * composite key, carry over the kjv rows, and materialise book rows for
         * each translation that has verses (copying translation-independent
         * canonical metadata from kjv). Runtime-imported translations (e.g. nkjv)
         * get their book rows via TranslationImporter.
         */
        private val MIGRATION_9_10 = Migration(9, 10) { db ->
            db.execSQL("DROP TABLE IF EXISTS `books_new`")
            db.execSQL(
                """CREATE TABLE IF NOT EXISTS `books_new` (
                    `id` INTEGER NOT NULL,
                    `translationId` TEXT NOT NULL,
                    `name` TEXT NOT NULL,
                    `abbreviation` TEXT NOT NULL,
                    `number` INTEGER NOT NULL,
                    `chapterCount` INTEGER NOT NULL,
                    `testament` TEXT NOT NULL,
                    `totalVerses` INTEGER NOT NULL,
                    PRIMARY KEY(`translationId`, `id`))"""
            )
            // Carry over existing (kjv) book rows.
            db.execSQL(
                "INSERT INTO `books_new` (translationId, id, name, abbreviation, number, chapterCount, testament, totalVerses) " +
                "SELECT translationId, id, name, abbreviation, number, chapterCount, testament, totalVerses FROM `books`"
            )
            // Materialise book rows for every other translation that has verses,
            // copying canonical metadata from the kjv rows (book data is translation-independent).
            db.execSQL(
                "INSERT OR IGNORE INTO `books_new` (translationId, id, name, abbreviation, number, chapterCount, testament, totalVerses) " +
                "SELECT v.translationId, k.id, k.name, k.abbreviation, k.number, k.chapterCount, k.testament, 0 " +
                "FROM `books` k CROSS JOIN (SELECT DISTINCT translationId FROM `verses` WHERE translationId != 'kjv') v " +
                "WHERE k.translationId = 'kjv'"
            )
            db.execSQL("DROP TABLE `books`")
            // Create the index only after the old table (and its same-named index) is
            // gone — SQLite index names are database-global, so IF NOT EXISTS would
            // otherwise see the old index and skip creating this one.
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_books_translationId` ON `books_new` (`translationId`)")
            db.execSQL("ALTER TABLE `books_new` RENAME TO `books`")
            // Fix per-book verse counts for the materialised rows
            // (verse data exists in `verses`; the v9 schema never tracked it
            // for non-kjv translations).
            db.execSQL(
                "UPDATE `books` SET totalVerses = (" +
                "SELECT COUNT(*) FROM `verses` v " +
                "WHERE v.translationId = `books`.translationId AND v.bookId = `books`.id) " +
                "WHERE totalVerses = 0"
            )
        }

        private val MIGRATION_5_6 = Migration(5, 6) { db ->
            db.execSQL("""
                CREATE VIRTUAL TABLE IF NOT EXISTS verses_fts_kjv USING fts5(
                    text,
                    bookId UNINDEXED,
                    chapter UNINDEXED,
                    verse UNINDEXED,
                    verseId UNINDEXED,
                    content='verses',
                    content_rowid='id',
                    tokenize='porter unicode61'
                )
            """)
            db.execSQL("""
                CREATE VIRTUAL TABLE IF NOT EXISTS verses_fts_web USING fts5(
                    text,
                    bookId UNINDEXED,
                    chapter UNINDEXED,
                    verse UNINDEXED,
                    verseId UNINDEXED,
                    content='verses',
                    content_rowid='id',
                    tokenize='porter unicode61'
                )
            """)
            db.execSQL("""
                CREATE VIRTUAL TABLE IF NOT EXISTS verses_fts_asv USING fts5(
                    text,
                    bookId UNINDEXED,
                    chapter UNINDEXED,
                    verse UNINDEXED,
                    verseId UNINDEXED,
                    content='verses',
                    content_rowid='id',
                    tokenize='porter unicode61'
                )
            """)
            db.execSQL("""
                CREATE VIRTUAL TABLE IF NOT EXISTS verses_fts_ylt USING fts5(
                    text,
                    bookId UNINDEXED,
                    chapter UNINDEXED,
                    verse UNINDEXED,
                    verseId UNINDEXED,
                    content='verses',
                    content_rowid='id',
                    tokenize='porter unicode61'
                )
            """)
            db.execSQL("""
                CREATE VIRTUAL TABLE IF NOT EXISTS verses_fts_bbe USING fts5(
                    text,
                    bookId UNINDEXED,
                    chapter UNINDEXED,
                    verse UNINDEXED,
                    verseId UNINDEXED,
                    content='verses',
                    content_rowid='id',
                    tokenize='porter unicode61'
                )
            """)
            db.execSQL("""
                CREATE VIRTUAL TABLE IF NOT EXISTS verses_fts_nkjv USING fts5(
                    text,
                    bookId UNINDEXED,
                    chapter UNINDEXED,
                    verse UNINDEXED,
                    verseId UNINDEXED,
                    content='verses',
                    content_rowid='id',
                    tokenize='porter unicode61'
                )
            """)

            // Triggers to keep FTS tables in sync with verses table
            db.execSQL("""
                CREATE TRIGGER IF NOT EXISTS verses_ai AFTER INSERT ON verses BEGIN
                    INSERT INTO verses_fts_kjv(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'kjv';
                    INSERT INTO verses_fts_web(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'web';
                    INSERT INTO verses_fts_asv(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'asv';
                    INSERT INTO verses_fts_ylt(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'ylt';
                    INSERT INTO verses_fts_bbe(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'bbe';
                    INSERT INTO verses_fts_nkjv(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'nkjv';
                END
            """)
            db.execSQL("""
                CREATE TRIGGER IF NOT EXISTS verses_ad AFTER DELETE ON verses BEGIN
                    DELETE FROM verses_fts_kjv WHERE rowid = old.id;
                    DELETE FROM verses_fts_web WHERE rowid = old.id;
                    DELETE FROM verses_fts_asv WHERE rowid = old.id;
                    DELETE FROM verses_fts_ylt WHERE rowid = old.id;
                    DELETE FROM verses_fts_bbe WHERE rowid = old.id;
                    DELETE FROM verses_fts_nkjv WHERE rowid = old.id;
                END
            """)
            db.execSQL("""
                CREATE TRIGGER IF NOT EXISTS verses_au AFTER UPDATE ON verses BEGIN
                    DELETE FROM verses_fts_kjv WHERE rowid = old.id;
                    DELETE FROM verses_fts_web WHERE rowid = old.id;
                    DELETE FROM verses_fts_asv WHERE rowid = old.id;
                    DELETE FROM verses_fts_ylt WHERE rowid = old.id;
                    DELETE FROM verses_fts_bbe WHERE rowid = old.id;
                    DELETE FROM verses_fts_nkjv WHERE rowid = old.id;
                    INSERT INTO verses_fts_kjv(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'kjv';
                    INSERT INTO verses_fts_web(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'web';
                    INSERT INTO verses_fts_asv(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'asv';
                    INSERT INTO verses_fts_ylt(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'ylt';
                    INSERT INTO verses_fts_bbe(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'bbe';
                    INSERT INTO verses_fts_nkjv(rowid, text, bookId, chapter, verse, verseId)
                    SELECT id, text, bookId, chapter, verse, id FROM verses WHERE id = new.id AND translationId = 'nkjv';
                END
            """)

            // Rebuild FTS tables from existing verses data
            db.execSQL("""
                INSERT OR REPLACE INTO verses_fts_kjv(rowid, text, bookId, chapter, verse, verseId)
                SELECT id, text, bookId, chapter, verse, id FROM verses WHERE translationId = 'kjv'
            """)
            db.execSQL("""
                INSERT OR REPLACE INTO verses_fts_web(rowid, text, bookId, chapter, verse, verseId)
                SELECT id, text, bookId, chapter, verse, id FROM verses WHERE translationId = 'web'
            """)
            db.execSQL("""
                INSERT OR REPLACE INTO verses_fts_asv(rowid, text, bookId, chapter, verse, verseId)
                SELECT id, text, bookId, chapter, verse, id FROM verses WHERE translationId = 'asv'
            """)
            db.execSQL("""
                INSERT OR REPLACE INTO verses_fts_ylt(rowid, text, bookId, chapter, verse, verseId)
                SELECT id, text, bookId, chapter, verse, id FROM verses WHERE translationId = 'ylt'
            """)
            db.execSQL("""
                INSERT OR REPLACE INTO verses_fts_bbe(rowid, text, bookId, chapter, verse, verseId)
                SELECT id, text, bookId, chapter, verse, id FROM verses WHERE translationId = 'bbe'
            """)
            db.execSQL("""
                INSERT OR REPLACE INTO verses_fts_nkjv(rowid, text, bookId, chapter, verse, verseId)
                SELECT id, text, bookId, chapter, verse, id FROM verses WHERE translationId = 'nkjv'
            """)
        }

/**
         * Version 4 → 5: Added locations and verse_location_links tables.
         * These tables support Bible geography features.
         * Safe to run multiple times (CREATE TABLE IF NOT EXISTS).
         */
        private val MIGRATION_4_5 = Migration(4, 5) { db ->
            db.execSQL("""
                CREATE TABLE IF NOT EXISTS locations (
                    id TEXT NOT NULL PRIMARY KEY,
                    name TEXT NOT NULL,
                    modern_name TEXT,
                    latitude REAL NOT NULL,
                    longitude REAL NOT NULL,
                    description TEXT NOT NULL,
                    category TEXT NOT NULL,
                    significance TEXT
                )
            """)
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_locations_category ON locations(category)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_locations_modern ON locations(modern_name)")

            db.execSQL("""
                CREATE TABLE IF NOT EXISTS verse_location_links (
                    locationId TEXT NOT NULL,
                    verseId INTEGER NOT NULL,
                    PRIMARY KEY (locationId, verseId)
                )
            """)
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_vll_verse ON verse_location_links(verseId)")
        }
    }
}
