package com.openbible.data.db

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.openbible.data.db.converter.Converters
import com.openbible.data.db.dao.BibleDao
import com.openbible.data.db.dao.BookmarkDao
import com.openbible.data.db.dao.CrossReferenceDao
import com.openbible.data.db.dao.HighlightDao
import com.openbible.data.db.dao.NoteDao
import com.openbible.data.db.dao.ReadingHistoryDao
import com.openbible.data.db.dao.ReadingPlanDao
import com.openbible.data.db.entity.BookEntity
import com.openbible.data.db.entity.BookmarkEntity
import com.openbible.data.db.entity.CrossReferenceEntity
import com.openbible.data.db.entity.HighlightEntity
import com.openbible.data.db.entity.NoteEntity
import com.openbible.data.db.entity.NoteImageEntity
import com.openbible.data.db.entity.NoteVerseLinkEntity
import com.openbible.data.db.entity.NotebookEntity
import com.openbible.data.db.entity.ReadingHistoryEntity
import com.openbible.data.db.entity.ReadingPlanDayEntity
import com.openbible.data.db.entity.ReadingPlanEntity
import com.openbible.data.db.entity.ReadingProgressEntity
import com.openbible.data.db.entity.TranslationEntity
import com.openbible.data.db.entity.VerseEntity

/**
 * OpenBible Room database.
 *
 * Schema is prepopulated with Bible text via createFromAsset().
 * The prepopulated database file lives at assets/databases/openbible.db
 * and is generated by a separate data import pipeline (see docs/).
 *
 * Version 1: initial schema with all 14 entities.
 * Version 2: added cross_references table.
 */
@Database(
    entities = [
        TranslationEntity::class,
        BookEntity::class,
        VerseEntity::class,
        BookmarkEntity::class,
        CrossReferenceEntity::class,
        HighlightEntity::class,
        NoteEntity::class,
        NoteImageEntity::class,
        NoteVerseLinkEntity::class,
        NotebookEntity::class,
        ReadingPlanEntity::class,
        ReadingPlanDayEntity::class,
        ReadingProgressEntity::class,
        ReadingHistoryEntity::class
    ],
    version = 2,
    exportSchema = true
)
@TypeConverters(Converters::class)
abstract class OpenBibleDatabase : RoomDatabase() {

    abstract fun bibleDao(): BibleDao
    abstract fun bookmarkDao(): BookmarkDao
    abstract fun crossReferenceDao(): CrossReferenceDao
    abstract fun highlightDao(): HighlightDao
    abstract fun noteDao(): NoteDao
    abstract fun readingPlanDao(): ReadingPlanDao
    abstract fun readingHistoryDao(): ReadingHistoryDao

    companion object {
        private const val DATABASE_NAME = "openbible.db"

        /**
         * Thread-safe singleton. Uses double-checked locking with @Volatile.
         * The prepopulated database is copied from assets on first access
         * if it exists — this is handled transparently by Room.
         */
        @Volatile
        private var INSTANCE: OpenBibleDatabase? = null

        fun getInstance(context: Context): OpenBibleDatabase {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: buildDatabase(context).also { INSTANCE = it }
            }
        }

        private fun buildDatabase(context: Context): OpenBibleDatabase {
            val builder = Room.databaseBuilder(
                context.applicationContext,
                OpenBibleDatabase::class.java,
                DATABASE_NAME
            )

            // Attempt to use prepopulated database from assets
            try {
                context.assets.open("databases/$DATABASE_NAME").use { }
                builder.createFromAsset("databases/$DATABASE_NAME")
            } catch (_: Exception) {
                // No prepopulated database found — will create empty schema.
                // Bible text must be imported via the data pipeline.
            }

            // Explicit migrations — never destroy user data.
            builder.addMigrations(MIGRATION_1_2)

            return builder.build()
        }

        /**
         * Use in tests to inject a prebuilt instance.
         */
        fun setTestInstance(database: OpenBibleDatabase?) {
            INSTANCE = database
        }

        // ── Migrations ──────────────────────────────────────────

        /**
         * Version 1 → 2: Added cross_references table.
         * Schema matches CrossReferenceEntity.
         * Safe to run multiple times (CREATE TABLE IF NOT EXISTS).
         */
        private val MIGRATION_1_2 = Migration(1, 2) { db ->
            db.execSQL("""
                CREATE TABLE IF NOT EXISTS cross_references (
                    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    fromVerseId INTEGER NOT NULL,
                    toBookId INTEGER NOT NULL,
                    toChapter INTEGER NOT NULL,
                    toVerseStart INTEGER NOT NULL,
                    toVerseEnd INTEGER,
                    relevance INTEGER NOT NULL DEFAULT 0
                )
            """)
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_cross_refs_from ON cross_references(fromVerseId)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_cross_refs_to ON cross_references(toBookId, toChapter, toVerseStart)")
        }
    }
}
